CKPT_PERIOD: 1
DEVICE: cuda
DISP_PERIOD: 100
EVAL_PERIOD: 1
EVAL_USE_CACHE: false
EVAL_USE_CBGM: true
EVAL_USE_GT: false
INPUT:
  BATCH_SIZE_TEST: 1
  BATCH_SIZE_TRAIN: 3
  DATASET: PRW
  DATA_ROOT: data/PRW
  MAX_SIZE: 1500
  MIN_SIZE: 900
  NUM_WORKERS_TEST: 1
  NUM_WORKERS_TRAIN: 3
MODEL:
  LOSS:
    BG_SIZE: 5000
    CQ_SIZE: 500
    LUT_SIZE: 482
    OIM_MOMENTUM: 0.5
    OIM_SCALAR: 30.0
    USE_SOFTMAX: true
  ROI_HEAD:
    BATCH_SIZE_TRAIN: 128
    BN_NECK: true
    DETECTIONS_PER_IMAGE_TEST: 300
    NEG_THRESH_TRAIN: 0.5
    NMS_THRESH_TEST: 0.4
    POS_FRAC_TRAIN: 0.5
    POS_THRESH_TRAIN: 0.5
    SCORE_THRESH_TEST: 0.5
  RPN:
    BATCH_SIZE_TRAIN: 256
    NEG_THRESH_TRAIN: 0.3
    NMS_THRESH: 0.7
    POST_NMS_TOPN_TEST: 300
    POST_NMS_TOPN_TRAIN: 2000
    POS_FRAC_TRAIN: 0.5
    POS_THRESH_TRAIN: 0.7
    PRE_NMS_TOPN_TEST: 6000
    PRE_NMS_TOPN_TRAIN: 12000
OUTPUT_DIR: ./exp_prw
SEED: 1
SOLVER:
  BASE_LR: 0.003
  CLIP_GRADIENTS: 10.0
  GAMMA: 0.1
  LR_DECAY_MILESTONES:
  - 8
  LW_BOX_CLS: 1
  LW_BOX_REG: 1
  LW_BOX_REID: 1
  LW_PROPOSAL_CLS: 1
  LW_PROPOSAL_REG: 10
  LW_RPN_CLS: 1
  LW_RPN_REG: 1
  MAX_EPOCHS: 25
  SGD_MOMENTUM: 0.9
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.0005
TF_BOARD: true
